name: taskmanager_tp8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_local_notifications: ^14.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.4
  


flutter:
  uses-material-design: true
  assets:
    - assets/tache.png
